///////////////////////////////////////////////////////////
//  ObslugaRaportow.cs
//  Implementation of the Class ObslugaRaportow
//  Generated by Enterprise Architect
//  Created on:      22-Nov-2017 3:41:03 PM
//  Original author: grzes
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DataServiceLayer.IService;

namespace DataServiceLayer.Service
{
    public class ObslugaRaportow : IObslugaRaportow
    {

        public DateTime dataRaportu;
        private int id_raportu;
        public char trescRaportu;
        public Kierownik m_Kierownik;

        public ObslugaRaportow()
        {

        }

        ~ObslugaRaportow()
        {

        }

        public void EdytujRaport()
        {

        }

        public void PrzegladajRaport()
        {

        }

        public void StworzRaport()
        {

        }

        public void UsunRaport()
        {

        }

    }//end ObslugaRaportow
}