///////////////////////////////////////////////////////////
//  Obs³ugaRachunku.cs
//  Implementation of the Class Obs³ugaRachunku
//  Generated by Enterprise Architect
//  Created on:      22-Nov-2017 3:41:26 PM
//  Original author: grzes
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DataServiceLayer.IService;

namespace DataServiceLayer.Service
{
    public class ObslugaRachunku : IObslugaRachunku
    {

        private int id_rachunku;
        public char SkladRachunku;
        public char wysokoscRachunku;

        public ObslugaRachunku()
        {

        }

        ~ObslugaRachunku()
        {

        }

        public void EdytujRachunek()
        {

        }

        public void OtworzRachunek()
        {

        }

        public void ZamknijRachunek()
        {

        }

    }//end Obs³ugaRachunku
}