//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase : DbContext
    {
        public DataBase()
            : base("name=DataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kasjer> Kasjers { get; set; }
        public virtual DbSet<Kierownik> Kierowniks { get; set; }
        public virtual DbSet<ObslugaRachunku> ObslugaRachunkus { get; set; }
        public virtual DbSet<ObslugaRaportow> ObslugaRaportows { get; set; }
        public virtual DbSet<Promocja> Promocjas { get; set; }
    }
}
