//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObslugaRachunku
    {
        public Nullable<int> id_rachunku { get; set; }
        public string skladRachunku { get; set; }
        public Nullable<double> wysokoscRachunku { get; set; }
        public int obslugaRachunkuID { get; set; }
        public Nullable<int> kasjerID { get; set; }
    
        public virtual Kasjer Kasjer { get; set; }
    }
}
