//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObslugaRaportow
    {
        public Nullable<int> id_raportu { get; set; }
        public string trescRaportu { get; set; }
        public Nullable<System.DateTime> dataRaportu { get; set; }
        public int obslugaRaportowID { get; set; }
        public int kasjerID { get; set; }
        public Nullable<int> kierownikID { get; set; }
    
        public virtual Kasjer Kasjer { get; set; }
        public virtual Kierownik Kierownik { get; set; }
    }
}
