//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporty_Rachunki
    {
        public int IdRaportu { get; set; }
        public int IdRachunku { get; set; }
        public int IdRaportyRachunki { get; set; }
    
        public virtual Rachunki Rachunki { get; set; }
        public virtual Raporty Raporty { get; set; }
    }
}
